plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

group = mod_group_id
version = mod_version

boolean dev = System.getenv('RELEASE') == null || System.getenv('RELEASE').equals('false')
ext.buildNumber = System.getenv('BUILD_NUMBER')
String gitHash = "${calculateGitHash() + (hasUnstaged() ? "-modified" : "")}"

base {
    archivesName = "create-extended-wrenches-${minecraft_version}"
    group = 'net.vercte.extendedwrenches'
    version = mod_version + (dev && buildNumber != null ? "-${buildNumber}" : '')
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

repositories {
    maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    maven { url = "https://mvn.devos.one/snapshots/" } // Create, Milk Lib
    maven { url = "https://mvn.devos.one/releases/" } // Porting Lib
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" } // ForgeConfigAPIPort
    maven { url = "https://maven.jamieswhiteshirt.com/libs-release" } // Reach Entity Attributes
    maven { url = "https://maven.blamejared.com" } // JEI
    maven { url = "https://maven.terraformersmc.com/" } // EMI
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    } // Every Compat
}

dependencies {
    minecraft("com.mojang:minecraft:${project.minecraft_version}")
    mappings loom.officialMojangMappings()

    modImplementation("net.fabricmc:fabric-loader:${project.loader_version}")

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_version}")

    modImplementation("com.simibubi.create:create-fabric:${create_version}-mc${minecraft_version}")

    modImplementation("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    modImplementation("mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}")
    modImplementation("mezz.jei:jei-${minecraft_version}-fabric:${jei_version}")

//    compileOnly fg.deobf("dev.emi:emi-forge:${emi_version}:api")
//    runtimeOnly fg.deobf("dev.emi:emi-forge:${emi_version}")

    modCompileOnly("curse.maven:selene-499980:7191950") // Moonlight Lib
    modCompileOnly("curse.maven:every-compat-628539:7223409")
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}"}
    }
}

String calculateGitHash() {
    try {
        def output = providers.exec {
            commandLine("git", "rev-parse", "HEAD")
        }
        return output.standardOutput.asText.get().trim()
    } catch (Throwable ignored) {
        return "unknown"
    }
}

boolean hasUnstaged() {
    try {
        def output = providers.exec {
            commandLine("git", "status", "--porcelain")
        }
        String result = output.standardOutput.asText.get().replace("/M gradlew(\\.bat)?/", "").trim()
        if (!result.isEmpty())
            println("Found stageable results:\n ${result}\n")
        return !result.isEmpty()
    } catch (Throwable ignored) {
        return false
    }
}