modLoader = "javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/vercte/extended-wrenches/"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}-${minecraft_version}"
displayName = "${mod_name}"
displayURL = "https://modrinth.com/mod/extended-wrenches/"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "assets/extendedwrenches/icon.png"

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId="create"
mandatory=true
versionRange="[6.0.4,6.0.5)"
ordering="NONE"
side="BOTH"
